### ISSUE TITLE
don't insert cell when push doesn't change board

### ISSUE THREAD

**Issue by genieCS** [genieCS/game2048-rs#40]

**Comment by panarch** [comment]
1. initial state
<img width="392" alt="image" src="https://user-images.githubusercontent.com/2025065/232021579-39a0d3bb-4d27-42c5-b07b-1e121845853f.png">

2. press left arrow key
3. new tile appears
<img width="405" alt="image" src="https://user-images.githubusercontent.com/2025065/232021837-16c1a192-69a9-4619-82e9-2f01d9d6948a.png">
